require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'reactstarter' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'reactstarterTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'reactstarter-tvOS' do
  # Pods for reactstarter-tvOS

  target 'reactstarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
